### ISSUE TITLE
Modify did.document so it adds "schema_version" and "property_list_name" in addition to "definition"

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/DID-matlab#10]
Modify did.document's reader so that when it builds the document_class.superclasses fields they have "schema_version" and "property_list_name" in addition to "definition"

Shufei - I made a new branch for you "Shufei_edits"

**Comment by stevevanhooser** [comment]
(in the vicinity of lines 389-396)

**Comment by sfchen196** [comment]
I am a bit confused about what I should change in the readjsonfilelocation() method. Is each superclass struct still uniquely defined by just the 'definition' field? If so, I think the following code can still concatenate the superclasses struct correctly?

```
s.document_class.superclasses = cat(1,s.document_class.superclasses(:),...
							s_super{i}.document_class.superclasses(:));
						[dummy,unique_indexes] = unique({s.document_class.superclasses.definition});
						s.document_class.superclasses = s.document_class.superclasses(unique_indexes);
```

**Comment by sfchen196** [comment]
I also see that the definition json files have not included the fields 'schema_version' and 'property_list_name' yet. Should I add those fields before I change the document.m?

**Comment by stevevanhooser** [comment]
Yes, but we want it to have a little more information in DID than it used to in NDI:

When it is built as a document, document_class.superclasses should have


| document_class.superclasses | Array of definition and versions of superclasses | An array of structures with entries definition and schema_version and property_list_name | Contains the NDI_definition strings and schema versions of all superclasses
| -- | -- | -- | --

In NDI, the only thing that was carried forward was the "definition" that was read right from the schema. Now we want to include a little more information so the validator can know which version it is validating.

Thanks!
Steve

**Comment by stevevanhooser** [comment]
_I also see that the definition json files have not included the fields 'schema_version' and 'property_list_name' yet. Should I add those fields before I change the document.m?_

Yes please! I see 'property_list_name' in base.json but schema_version is still called class_version (needs to be updated)

Thanks
Steve

**Comment by sfchen196** [comment]
I see, so if two parent docs of a child doc have the same 'definition' field but different 'schema_version' field (if that's possible), then we should keep both of the structs in the 'superclasses' array of the child doc? So each superclass struct is uniquely identified by 'definition' and 'schema_version' fields, correct? What about the 'property_list' field? Is it completely dependent on the 'definition' string?

**Comment by stevevanhooser** [comment]
Oh, right good thought.

I think the first version of the superclass that is encountered should stand. That is what will contribute the data to the subfields under the 'property_list_name'.

'property_list_name' should just be listed for each superclass along with the definition location and version. It allows the reader to know which superclass contributed which properties without loading in all the definitions. It's true that it is not enough information to validate the document but it would allow a human reader to understand how the document was built.

Thanks!
Steve

**Comment by stevevanhooser** [comment]
Shufei did it
