### ISSUE TITLE
Modify did.document so that it uses the new $ substitution options

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/DID-matlab#11]
Hi Shufei - 

I changed the did global configuration variable that describes file paths from the way it was done in NDI. 

Now the variable did_globals (made available by calling `did.globals`) has, among others, the following fields:

```
did_globals.path.definition_names = {'$DIDDOCUMENT_EX1' '$DIDSCHEMA_EX1'};
did_globals.path.definition_locations = ...
	{  [did_globals.path.path filesep 'example_schema' filesep 'demo_schema1' filesep 'database_documents'] ...
	   [did_globals.path.path filesep 'example_schema' filesep 'demo_schema1' filesep 'schema_documents'] };
```

That is, I changed the previous behavior in NDI of having a single $VARIABLE that mapped to a single location to having any number of strings that begin with $ map to any number of locations. However, I did not modify `did.document` so that it actually implements this.

For the current version, I made a note on lines 426-428 that I just had it search for the example schema that I included here. But it needs to be able to use the full list of $ values for replacement. 

					% temporary : I've fixed the search string so it can only be DIDDOCUMENT_EX1 and gets replaced with the first
					%           : did.path.documentpath{1} entry
					%           : Should search through all the names

Can you please make the fix to `did.document`?

Thanks!
Steve

**Comment by sfchen196** [comment]
No problem. I will do that.

**Comment by stevevanhooser** [comment]
done
