### ISSUE TITLE
after merge, did.test.test_did_validator fails

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/DID-matlab#23]
Hi @zhaoy17 and @sfchen196 -

I just merged all the branches, thanks for your work over the past couple months!

The document test is working, but for some reason I get the following with did.test.test_did_validator:

Error using did.validate (line 103)
Fail to verify the ndi_document. This is likely caused by json-schema not formatted correctlyHere is the detail Java exception error: Reference to non-existent field
'this'.

Error in did.test.test_did_validator (line 18)
    validator = did.validate(subject_doc);

I wonder if I'm missing a json schema possibly? (Maybe something that isn't in the master/validator2?)

Thanks
Steve

**Comment by zhaoy17** [comment]
Hi professor, I'll take a look at it when I get a chance.

**Comment by zhaoy17** [comment]
I think the name of a variable on line 92 that is referenced later in the code has been accidentally changed. I changed that variable name from "validate_obj" to "did_validate_obj", then everything works.

**Comment by stevevanhooser** [comment]
great, it works! thanks!
