### ISSUE TITLE
filecache write error, Windows R2022a

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/DID-matlab#29]
(Look into this)

> FYI, I confirmed that the filecache write error is due to an internal bug in Matlab R2022a or newer, at least on Windows (I'm not sure about MacOS/Linux).

**Comment by altmany** [comment]
R2022a (not ok):
```
>> [fid,msg] = fopen([userpath '\test.txt'], 'wt')
fid =
    -1
msg =
    'Permission denied'
```

R2021b (ok):
```
>> [fid,msg] = fopen([userpath '\test.txt'], 'wt')
fid =
     3
msg =
  0×0 empty char array
```

**Comment by altmany** [comment]
It looks like this internal Matlab bug is fixed in R2022b, so only problematic on R2022a
