### ISSUE TITLE
sql database construction note

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/DID-matlab#30]
Hi Yair - 

I noticed a use case that might impact how you build the database.

Consider the search operation 'isa':

`stim_pres = S.database_search(ndi.query('','isa','stimulus_presentation',''))
`

which produces for this case I am working on all documents that are of type 'stimulus_presentation':

```
stim_pres =
  1×11 cell array
  Columns 1 through 5
    {1×1 ndi.document}    {1×1 ndi.document}    {1×1 ndi.document}    {1×1 ndi.document}    {1×1 ndi.document}
  Columns 6 through 10
    {1×1 ndi.document}    {1×1 ndi.document}    {1×1 ndi.document}    {1×1 ndi.document}    {1×1 ndi.document}
  Column 11
    {1×1 ndi.document}
```

To make this easy in the sql, one might want to have an enumerated table of all document classes, and an array for each document in the document table that lists the classes to which the document belongs (superclasses plus its own class), so that the query can run quickly. 

Hopefully this make sense...

Thanks
Steve

**Comment by altmany** [comment]
In this case, instead of the SELECT query returning docs.doc_id, it would return docs.json_code - the rest of the SQL query remains unchanged

**Comment by altmany** [comment]
How should the JSON field (docs.json_code) be populated? by which class method and with which value?

**Comment by stevevanhooser** [comment]
It should be the output of jsonencode. We run the version with NaN allowed (JSON natively does not support NaN but many readers and writers do, including Matlab). We have a wrapper function vlt.data.jsonencodenan.m that catches Matlab’s changing behavior over the last few years:

https://github.com/VH-Lab/vhlab-toolbox-matlab/blob/master/%2Bvlt/%2Bdata/jsonencodenan.m

**Comment by stevevanhooser** [comment]
Great, thanks! Do you want to proceed to handling the other search cases first or to have me test the code that is here first? It would be helpful to have some test code to evaluate in +did/+test

Thanks!
Steve

**Comment by altmany** [comment]
All done & committed as discussed earlier today. 
I decided to have the search function still return doc_ids (not doc objects) in a cell-array; a separate public method (`doc_ids_to_objects`) which returns an array of `did.document` objects that correspond to the specified doc_id(s).
