### ISSUE TITLE
on sql branch, did.test.test_did_branches fails

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/DID-matlab#32]
The reason seems to be that

db.get_branch_parent(branch_name)

returns a 1-element cell array with an empty string when branch_name has no parent, instead of an empty cell array.

Thanks
Steve

**Comment by altmany** [comment]
`db.get_branch_parent(branch_name)` now returns a string rather than a cell array. If no parent found (root branch), an empty string (`''`) is returned.
