### ISSUE TITLE
did.database.add_doc and did.database.remove_doc should accept cell array (or square array) inputs

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/DID-matlab#35]

**Comment by altmany** [comment]
Note: the main class methods were renamed to `add_docs()` and `remove_docs()`; the original methods names (`add_doc()`, `remove_doc()`) are preserved for backward-compatibility as hidden methods, passing the input value(s) to the main methods. This will keep the existing test functions and implementations working, but new code should really use the new methods names.

**Comment by stevevanhooser** [comment]
Thanks, tested, and it works!
