### ISSUE TITLE
Do we need base.type?

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/DID-matlab#4]
Or, is there a good reason to keep it?

**Comment by stevevanhooser** [comment]
Let's remove this. 

@yannanz913 : Can you please remove it from

a) base.json in the example documents?
b) The wiki https://github.com/VH-Lab/DID-matlab/wiki/Discussion-on-DID-document-core
c) The DISCUSSION.md file?

I made a new branch "yannan_edits" for you to work on.

Thanks
Steve

**Comment by yannanz913** [comment]
Sure! I noticed that the base.json document does not have contents under the "type" category. Should I just simply remove the "type"?

**Comment by stevevanhooser** [comment]
Yes please!

**Comment by yannanz913** [comment]
"base.type" has been removed from the files! If other changes need to be made, just let me know:)

**Comment by stevevanhooser** [comment]
Thanks! All done
