### ISSUE TITLE
Bug: did.database.findfilematch fails if input "expectedName" ends with # symbol

### ISSUE THREAD

**Issue by ehennestad** [VH-Lab/DID-matlab#73]
I get the following error for `did.database.findfilematch` due to some undefined variables on the line linked below

```
did.database.findfilematch('ANYTHING_#', 'ANYTHING_5')
Undefined variable 'docNamesList'.

Error in did.database.findfilematch (line 1617)
                      rest_of_name = docNamesList{i}(numel(expectedNamesList{indexes(k)}):end);
```

https://github.com/VH-Lab/DID-matlab/blob/23d6987d65a347b5da6921c99ec1a75123bb4e49/%2Bdid/database.m#L1603

**Comment by stevevanhooser** [comment]
Yeah that seems to be a copy/paste error or something...I have a fix testing...
