### ISSUE TITLE
Bug: Superclass for did.implementations.postgresdb does not exist

### ISSUE THREAD

**Issue by ehennestad** [VH-Lab/DID-matlab#74]
Specifies superclass `database`, but this class does not exist in the namespace. 

Should it be `did.database`? 

However,  the constructor also assigns a database object to a property, so relationship is a bit unclear

**Comment by stevevanhooser** [comment]
`postgresdb` is an older piece of code. We could probably just remove it. If we wanted to bring it back we would probably build out `sqldb` and then make both `sqlite` and `postgresdb` subclasses. I don't know if we should remove them or put them in a folder that says "preliminary" and maybe change their extensions to `.m0` so they don't count as code.

**Comment by ehennestad** [comment]
Maybe move it to a different branch?

**Comment by ehennestad** [comment]
Added new issue:
https://github.com/VH-Lab/DID-matlab/issues/81
